/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import src.utilities.*;

public class App {

    public static void main(final String[] args) {
        TetrisUI tetris = new TetrisUI();
        tetris.init();
    }
}


